### ISSUE TITLE
NestJS in nx workspace as a lambda function in AWS

### ISSUE THREAD

**Issue by MitkoTschimev** [Dev-Thought/ng-deploy-it#15]
As a developer, I want to have the possibility that I can deploy my nestjs application with infrastructure as code to AWS.

**Comment by ndimer** [comment]
Any documentation of this feature?

**Comment by craigbroadman** [comment]
> Any documentation of this feature?

Here a link to the docs....
https://docs.nestjs.com/faq/serverless
