### ISSUE TITLE
NestJS in nx workspace as an Azure function

### ISSUE THREAD

**Issue by MitkoTschimev** [Dev-Thought/ng-deploy-it#16]
As a developer, I want to have the possibility that I can deploy my nestjs application with infrastructure as code to Azure.

**Comment by ntziolis** [comment]
First thing we need is a [builder](https://github.com/nrwl/nx/blob/master/packages/node/builders.json), becasue
 - azure functions require js files per function
 - all available builders create a single bundle

I have manually configured an nx app (based on `@nrwl/node` that contains an azure function project which builds fine. But without the ability to output multiple files when building we would only able to create a single function per project :)

I'm no expert in webpack but looking at:
- the current node [webpack config](https://github.com/nrwl/nx/blob/master/packages/node/src/utils/node.config.ts) 
- and [this](https://dev.to/dnasir/azure-functions-node-js-typescript-webpack-a3m) article

It looks doable without major surgery. That said I never build an angular builder :)

After getting azure functions to build the next would be to tackle:
- schematic for creating an azure function app
- schematic for adding new function

After that one can look creating schematics for specific apps like nest.

**Comment by ntziolis** [comment]
Update:
- this following [azure function webpack plugin ](https://github.com/PageProofCom/azure-functions-webpack-plugin) looks promising. Its based on the previously azure-fucntion-pack package which is no longer maintained
- it scans the entry directory for `functions.json` files and uses those to build the individual functions
- we would also need to resolve tsconfig patsh properly, luckily there seems to be a very well supported [webpack plugin](https://www.npmjs.com/package/tsconfig-paths-webpack-plugin) for handling that

**Comment by MitkoTschimev** [comment]
Thanks a lot for all the input! I will try to check how I can fit it into this project! But let's start with small steps. So first thing we should do is to be able to deploy a nestjs app with 1 function. than we can go ahead with splitting in multiple functions.

I know from Kamil they they are working on a feature there where you can set separate functions via decorator on modules. Hope this lands soon to nestjs
https://github.com/nestjs/serverless-core

**Comment by MitkoTschimev** [comment]
Not easy to integrate it as easy as possible :(

2 options are there:

1. you need to maintain a separate package.json with all the dependencies for the node / nest app
2. Find a way to automatically align all required dependencies. Here I am trying at the moment this package: https://github.com/zeit/ncc but seems not to work. Trying still to make a workable solution with it.

**Comment by MitkoTschimev** [comment]
Ok figured out that the problem was just a wrong runtime version of node on azure :) so ncc is working amazingly! I will go for it

**Comment by MitkoTschimev** [comment]
Implemented first version by #24
